//! Analysis-report export (`--out <file>`).
//!
//! Zero dependencies by design: the report is assembled from the same
//! source-of-truth display the CLI prints (`app::collect_display_lines`,
//! `fundamental::render_fundamental_display`) plus the LLM commentary, and written
//! as **HTML**, **Markdown**, or **plain text** — chosen by the file extension.
//! There is deliberately no PDF library; to get a PDF, open the `.html` in a
//! browser and "Print → Save as PDF" (keeps the binary single-file and auditable).

use crate::config::Config;
use crate::fundamental::FundamentalData;
use crate::technical::types::TechnicalDataGuard;
use anyhow::{Context, Result};

/// Report output format, selected from the output path's extension.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Format {
    Html,
    Markdown,
    Text,
}

impl Format {
    fn from_path(path: &str) -> Self {
        let lower = path.to_ascii_lowercase();
        if lower.ends_with(".html") || lower.ends_with(".htm") {
            Format::Html
        } else if lower.ends_with(".md") || lower.ends_with(".markdown") {
            Format::Markdown
        } else {
            // Anything else (incl. .txt or no/unknown extension) → plain text.
            Format::Text
        }
    }
}

/// Strip ANSI escape sequences — the CLI colorizes its output, but a file should
/// be plain. Removes `ESC[…<letter>` (SGR/CSI) runs.
fn strip_ansi(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\u{1b}' {
            if chars.peek() == Some(&'[') {
                chars.next();
                for c2 in chars.by_ref() {
                    if c2.is_ascii_alphabetic() {
                        break;
                    }
                }
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Minimal HTML text escaping.
fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(c),
        }
    }
    out
}

/// The rendered, ANSI-stripped pieces of a report (shared by every format).
struct Parts<'a> {
    title: &'a str,
    tf: &'a str,
    as_of: &'a str,
    technical: &'a str,
    fundamental: &'a str,
    commentary: &'a str,
}

struct Labels {
    tf: &'static str,
    as_of: &'static str,
    technical: &'static str,
    fundamental: &'static str,
    commentary: &'static str,
    footer: &'static str,
}

fn labels(lang: &str) -> Labels {
    if lang == "ja" {
        Labels {
            tf: "足種",
            as_of: "データ最新",
            technical: "テクニカル分析",
            fundamental: "ファンダメンタル",
            commentary: "AI 解説",
            footer: "XOKSA が生成。上記の数値は Rust で算出した確定データ（Source of Truth）で、AI 解説はそれを説明したものです。投資助言ではありません。",
        }
    } else {
        Labels {
            tf: "Timeframe",
            as_of: "As of",
            technical: "Technical Analysis",
            fundamental: "Fundamentals",
            commentary: "AI Commentary",
            footer: "Generated by XOKSA. The values above are computed in Rust (source of truth); the AI commentary explains them. Not investment advice.",
        }
    }
}

/// Write the analysis report to `path`, choosing HTML / Markdown / text by
/// extension. `commentary` may be empty (e.g. `--no-llm`).
pub fn write_report(
    path: &str,
    config: &Config,
    guard: &TechnicalDataGuard,
    fundamental_data: Option<&FundamentalData>,
    commentary: &str,
) -> Result<()> {
    let technical = strip_ansi(&crate::app::collect_display_lines(config, guard).join("\n"));
    let fundamental = fundamental_data
        .map(|d| {
            strip_ansi(&crate::fundamental::render_fundamental_display(d, &config.lang).join("\n"))
        })
        .unwrap_or_default();
    let commentary = strip_ansi(commentary);

    let title = format!("{} ({})", guard.get_ticker(), guard.get_name());
    let tf = config.analysis_mode.as_str();
    let as_of = guard
        .get_market_data_latest_time()
        .or_else(|| guard.get_analyzed_at())
        .unwrap_or("");
    let lab = labels(&config.lang);
    let parts = Parts {
        title: &title,
        tf,
        as_of,
        technical: &technical,
        fundamental: &fundamental,
        commentary: &commentary,
    };

    let body = match Format::from_path(path) {
        Format::Html => render_html(&parts, &lab, &config.lang),
        Format::Markdown => render_markdown(&parts, &lab),
        Format::Text => render_text(&parts, &lab),
    };

    std::fs::write(path, body).with_context(|| format!("failed to write report to {path}"))?;
    Ok(())
}

fn render_html(p: &Parts, lab: &Labels, lang: &str) -> String {
    let mut sections = format!(
        "<h2>{}</h2>\n<pre class=\"mono\">{}</pre>\n",
        html_escape(lab.technical),
        html_escape(p.technical)
    );
    if !p.fundamental.trim().is_empty() {
        sections.push_str(&format!(
            "<h2>{}</h2>\n<pre class=\"mono\">{}</pre>\n",
            html_escape(lab.fundamental),
            html_escape(p.fundamental)
        ));
    }
    if !p.commentary.trim().is_empty() {
        sections.push_str(&format!(
            "<h2>{}</h2>\n<div class=\"prose\">{}</div>\n",
            html_escape(lab.commentary),
            html_escape(p.commentary)
        ));
    }
    format!(
        "<!doctype html>\n<html lang=\"{lang}\"><head><meta charset=\"utf-8\">\
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\
<title>XOKSA — {title_esc}</title>\n<style>\
:root{{color-scheme:light}}\
body{{font:14px/1.6 system-ui,'Segoe UI','Noto Sans JP',sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#111}}\
h1{{font-size:1.4rem;margin:0 0 .2rem}}\
h2{{font-size:1.1rem;border-bottom:1px solid #ddd;padding-bottom:.2rem;margin:1.6rem 0 .6rem}}\
.meta{{color:#666;font-size:.9rem;margin:0 0 1rem}}\
pre.mono{{background:#f6f8fa;border:1px solid #e1e4e8;border-radius:6px;padding:.8rem;overflow-x:auto;font:12px/1.5 ui-monospace,Menlo,Consolas,monospace;white-space:pre}}\
.prose{{white-space:pre-wrap}}\
footer{{margin-top:2rem;color:#888;font-size:.8rem;border-top:1px solid #eee;padding-top:.6rem}}\
@media print{{body{{margin:0;max-width:none}}pre.mono{{white-space:pre-wrap;word-break:break-word}}}}\
</style></head><body>\n\
<h1>{title_esc}</h1>\n\
<p class=\"meta\">{tf_lab}: {tf_esc} · {asof_lab}: {asof_esc}</p>\n\
{sections}\
<footer>{footer}</footer>\n\
</body></html>\n",
        title_esc = html_escape(p.title),
        tf_lab = html_escape(lab.tf),
        tf_esc = html_escape(p.tf),
        asof_lab = html_escape(lab.as_of),
        asof_esc = html_escape(p.as_of),
        footer = html_escape(lab.footer),
    )
}

fn render_markdown(p: &Parts, lab: &Labels) -> String {
    let mut out = format!(
        "# {title}\n\n**{tf_lab}:** {tf} · **{asof_lab}:** {as_of}\n\n## {tech}\n\n```\n{technical}\n```\n",
        title = p.title,
        tf_lab = lab.tf,
        tf = p.tf,
        asof_lab = lab.as_of,
        as_of = p.as_of,
        tech = lab.technical,
        technical = p.technical,
    );
    if !p.fundamental.trim().is_empty() {
        out.push_str(&format!(
            "\n## {}\n\n```\n{}\n```\n",
            lab.fundamental, p.fundamental
        ));
    }
    if !p.commentary.trim().is_empty() {
        out.push_str(&format!("\n## {}\n\n{}\n", lab.commentary, p.commentary));
    }
    out.push_str(&format!("\n---\n_{}_\n", lab.footer));
    out
}

fn render_text(p: &Parts, lab: &Labels) -> String {
    let rule = "=".repeat(60);
    let mut out = format!(
        "{rule}\n {title}\n {tf_lab}: {tf} · {asof_lab}: {as_of}\n{rule}\n\n--- {tech} ---\n{technical}\n",
        title = p.title,
        tf_lab = lab.tf,
        tf = p.tf,
        asof_lab = lab.as_of,
        as_of = p.as_of,
        tech = lab.technical,
        technical = p.technical,
    );
    if !p.fundamental.trim().is_empty() {
        out.push_str(&format!(
            "\n--- {} ---\n{}\n",
            lab.fundamental, p.fundamental
        ));
    }
    if !p.commentary.trim().is_empty() {
        out.push_str(&format!("\n--- {} ---\n{}\n", lab.commentary, p.commentary));
    }
    out.push_str(&format!("\n{}\n", lab.footer));
    out
}

#[cfg(test)]
mod tests {
    use super::{strip_ansi, Format};

    #[test]
    fn format_from_extension() {
        assert!(matches!(Format::from_path("r.html"), Format::Html));
        assert!(matches!(Format::from_path("R.HTM"), Format::Html));
        assert!(matches!(Format::from_path("r.md"), Format::Markdown));
        assert!(matches!(Format::from_path("r.markdown"), Format::Markdown));
        assert!(matches!(Format::from_path("r.txt"), Format::Text));
        assert!(matches!(Format::from_path("report"), Format::Text)); // unknown → text
        assert!(matches!(Format::from_path("r.pdf"), Format::Text)); // no PDF lib → text
    }

    #[test]
    fn strips_ansi_sequences() {
        assert_eq!(strip_ansi("\u{1b}[31mred\u{1b}[0m"), "red");
        assert_eq!(strip_ansi("plain"), "plain");
        assert_eq!(strip_ansi("a\u{1b}[1;32mb\u{1b}[0mc"), "abc");
    }
}
